### ISSUE TITLE
[Bug] StoreSession can't be "session"

### ISSUE THREAD

**Issue by MoKhajavi75** [gram-js/gramjs#480]
Hey

I used `session` as `sessionName` but I found out it won't save the session data if the name is `session`.

So, this code works:

```ts
const client = new TelegramClient(new StoreSession('test'), config.apiId, config.apiHash, {});
```

but this does NOT work:

```ts
const client = new TelegramClient(new StoreSession('session'), config.apiId, config.apiHash, {});
```

**Comment by kubk** [comment]
Wow, it's a very strange issue that happened to me too. @painor Will you accept a PR that fixes it if it's ready?

**Comment by painor** [comment]
Yes I would @kubk

**Comment by kubk** [comment]
Hi @painor 

My guess the reason of the issue is that 'session' key is being used by `store2` internally and it leads to unintended overrides: https://github.com/nbubna/store/blob/0216588bc53505e290c537aaae2c52fa5ad47df8/src/store2.js#L272

The issue we're trying to solve is that when a user of gramjs is using the library for the first time, it's tempting to name the session folder 'session'. However, doing so doesn't lead to persisting anything. The use may think the issue is related to their code or folder permissions. It's not obvious that the session name is the reason of the issue.

To solve this, I suggest forbidding the use `session` as a name and throwing an exception instead. Another option could be to prefix the session name with something like `gramjs_${sessionName}`, but I'm afraid it might cause a backward compatibility break.

If you're OK with that I'll implement a PR that throw exception inside `StoreSession` when the key is `session`

**Comment by kubk** [comment]
@painor I believe this can closed.
