### ISSUE TITLE
[HELP] Api.InputChannel example

### ISSUE THREAD

**Issue by snowshoes** [gram-js/gramjs#84]
Hello, Could someone help me figure out how to set appropriate type for parameter `accessHash` in `Api.InputChannel` API ?

Here is the example of my code, all parameters are pseudo numbers but of the same digits as the real one

```
const result = await client.invoke(
        new Api.channels.GetParticipants({
            channel: new Api.InputChannel({channelId: 1306372915, accessHash: BigInt(-2089358348472948573)})
        })
```

But I got the following error:

```
(node:32673) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getBytes' of undefined
    at argToBytes (/Users/swen/Downloads/Repository/telebot/node_modules/telegram/tl/api.js:122:22)
    at VirtualClass.getBytes (/Users/swen/Downloads/Repository/telebot/node_modules/telegram/tl/api.js:378:42)
```
It seems that accessHash cannot be parsed by `getBytes` method in `telegram/tl/api.js`, and I also tried import `big-integer` dependency as type suggested.

```
import bigInt from 'big-integer'

const result = await client.invoke(
        new Api.channels.GetParticipants({
            channel: new Api.InputChannel({channelId: 1306372915, accessHash: bigInt(-2089358348472948573)})
        })

```
which results in the same error.

So how to correctly parse `accessHash` parameter in this case ?

Thanks in advance

**Comment by painor** [comment]
the error is not related to the `accessHash` (which is being passed wrongly). if you try to type that big number in the console it would return `-2089358348472948500` so if you wanted to use big numbers either use `-2089358348472948573n`  (notice the n) or `bigInt("-2089358348472948573")` (as a string)

That issue you are facing is because you didn't pass all the required arguments of `channels.GetParticipants` (like filter)

I'd suggest instead of calling that Raw method to use `client.getParticipants` which handles all that for you https://painor.gitbook.io/gramjs/getting-started/available-methods/getting-participants-of-a-group-channel

**Comment by snowshoes** [comment]
@painor Thank you so much for your help, I'll give it a try then get back with the result

**Comment by snowshoes** [comment]
@painor  Thanks again for sheding light on my problem, it's much easier with `getParticipants()` to retrieve all members in a group, the problem has been solved, cheers!
