### ISSUE TITLE
Process TL schema in runtime

### ISSUE THREAD

**Issue by Ajaxy** [gram-js/gramjs#9]
Thanks for the great work. What do you think about not generating content for `/gramjs/tl/*` but rather parsing and processing the TL schema files in runtime? The folder now is very heavy (2+ mb), and it could be x10 less. All the logic that is used for generating those files can be used the same way during the runtime.

**Comment by painor** [comment]
We're actually thinking of doing something similar just after finishing making sessions work well. 
The problem is we're also planning on using typescript/add types to make coding it easier so processing them at RAW time means you won't be able to access types.

We are thinking of lowering the size by having generic functions/types but a single function that parses which will hopefully reduce the size a lot and still be typed/fast that would look something like. 

```
def doTheMagic(code, params):
  *serialiazes params knowing it'll invoke the function determined by code*

def sendMessage(peer, msg):
  return doTheMagic(0xMsgCode, (peer, msg))
```

**Comment by Ajaxy** [comment]
Yes, this sounds great!

**Comment by YouTwitFace** [comment]
@Ajaxy Feel free to join the discussion on Telegram. https://t.me/GramJSChat

**Comment by painor** [comment]
well it does that now.
